import { data } from "autoprefixer";
import Head from "next/head";
import { supabase } from "../utils/supabaseClient";

export default function Home({ posts }) {
  console.log(supabase.auth.user());
  console.log(supabase.auth.session());
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <pre>{JSON.stringify(posts, null, 2)}</pre>
    </div>
  );
}

export const getStaticProps = async () => {
  // query to get the posts
  const { data: posts, error } = await supabase.from("posts").select("*");

  if (error) {
    throw new Error(error);
  }

  return {
    props: {
      posts: posts,
    },
  };
};
