import Head from "next/head";
import Features from "../components/Features";
import Header from "../components/Header";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Traffic Website Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="w-full min-h-screen font-Poppins bg-gray-900">
        <div className="max-w-7xl mx-auto py-10 px-8">
          <Header />
          <Hero />
          <Features/>
        </div>
      </div>
    </div>
  );
}
