import Head from "next/head";
import Download from "../components/Download";

import Framework from "../components/Framework";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Improvements from "../components/Improvements";

export default function Home() {
  return (
    <div className="font-Poppins bg-gray-900 h-screen text-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      {/* hero */}
      <Hero />
      {/* framework */}
      <Framework />
      {/* improvements */}
      <Improvements />
      {/* download */}
      <Download />
    </div>
  );
}
