import Head from "next/head";
import Download from "../components/Download";

import Framework from "../components/Framework";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Improvements from "../components/Improvements";

export default function Home() {
  return (
    <div className="text-white items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
 
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <Header />
          <Hero />
          <Framework />
          <Improvements />
          <Download />
    </div>
  );
}
